### ISSUE TITLE
Create one common CMakeLists.txt in the root

### ISSUE THREAD

**Issue by knatten** [zivid/cpp-extra-samples#7]
In PR #2 a discussion was started about factoring out a common CMakeLists.txt in the project root. This is a bigger issue, and shouldn't block #2 from being merged, so lets' do that as a separate issue instead.

**Comment by knatten** [comment]
There are (at least) three good reasons to have a common `CMakeLists.txt` in the root:

- One file to open in you IDE and get all the samples loaded
- Easily build all samples with one command
- Avoiding code duplication

The last point could also be solved by having one `CMakeLists.txt` per directory like today.

A few questions for @SatjaSivcev and the team:

When we fix this, do we still want to group the samples in the sub directories we have today? Are the directories there just because of technical reasons (dependencies), or do we want to keep using sub directories because we think it's nice?

If we think it's nice with sub directories: Does the current grouping make sense, or would it be better to group by something else, like for instance what the samples are *doing* rather than how they're implemented?

If we keep grouping by dependencies, what do we do when we get a sample which depends on two things, for instance both OpenCV and PCL?

**Comment by SatjaSivcev** [comment]
The only reason I have separated the samples is the dependencies. I wanted to avoid that a customer who wants to test a sample program that doesn't require any dependencies, has to have all the dependencies in order to build the samples. I also think it is nice (visually) to group them by dependencies. I think grouping by what they do would be complicated. But I don't know what is the best way to do this, including the grouping, especially for the reason that one sample may require both OpenCV and PCL. Is it possible to have one Cmake file in the root and that only those samples for which dependencies are found get built?

What do you suggest @knatten?

**Comment by knatten** [comment]
Yeah I have a prototype for doing something like that. Everything in one `CMakeLists.txt` in the root, and only building the ones we have dependencies for. Then the how we group stuff in directories is orthogonal to dependencies and we can organize things however we feel like.

What we need to decide on is what the default behaviour should be. In my prototype, you have to explicitly say that you don't want to build examples with a certain dependency. So for each dependency, you either have to provide it or say you're ok with not having it. That way you won't accidentally miss some of the samples. The other solution would be to silently just not build those  examples, and maybe add a warning. But then they might not turn up in IDEs either. Let's experiment a bit and discuss irl.

**Comment by knatten** [comment]
Fixed in #23
